version: '3'
services:
  bot:
    container_name: "gpt-bot"
    restart: "unless-stopped"
    build: 
      context: "./bot"
      dockerfile: Dockerfile.prod
    volumes:
      - ./bot:/var/www/api
    network_mode: "host"